name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: windows-latest  
    env:
      Solution_Name: RentACar.sln                      # Replace with your solution name, i.e. MyWpfApp.sln.

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
      
    - name: Restore the application
      run: dotnet restore

    - name: Build
      run: dotnet build 
